In [1]:
import numpy as np

# Punto 1 Crear un array de numpy que contenga los números del 1 al 20. Mostrar el array, su tamaño y su tipo de dato.

In [3]:
array = np.arange(1,29)
array.shape
array.size
array.dtype
print(array)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]


# Punto 2 Crear una matriz 5x5 de ceros y una matriz 5x5 de unos. Sumarlas y mostrar el resultado.

In [2]:
matriz1 = np.zeros((5,5))
matriz2 = np.ones((5,5))
suma = matriz1 + matriz2
print(suma)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Punto 3 Crear un array con números del 10 al 50 con paso 5.

In [14]:
np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

# Punto 4 Crear una matriz identidad de tamaño 4x4.

In [2]:
lista_2D = np.eye(4)
print(lista_2D)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# punto 5 Crear un array con números del 1 al 12 y transformarlo en una matriz 3x4.

In [18]:
array1 = np.arange(1,13).reshape(3,4)
print(array1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# punto 6 Dado el array [12, 45, 7, 23, 56, 89, 34], calcular el promedio, el valor máximo, el valor mínimo y la  desviación estándar.

In [2]:
lista = [12, 45, 7, 23, 56, 89, 34]
array = np.array(lista)
print(min(array))
print(max(array))
print(array.mean())
print(array.std())
print(array.sum())

7
89
38.0
26.32760636941492
266


# punto 7 Crear dos arrays A=[1,2,3,4,5] y B=[10,20,30,40,50]. Calcular suma, resta, multiplicación y división elemento a elemento.

In [4]:
A=[1,2,3,4,5]
B=[10,20,30,40,50]
arrayA= np.array(A)
arrayB = np.array(B)

suma = arrayA + arrayB
resta = arrayA - arrayB
multiplicacion = arrayA * arrayB
division = arrayA / arrayB


print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

Suma: [11 22 33 44 55]
Resta: [ -9 -18 -27 -36 -45]
Multiplicación: [ 10  40  90 160 250]
División: [0.1 0.1 0.1 0.1 0.1]


# 8. Dado el array [3, 8, 15, 20, 7, 12, 18, 1], obtener un nuevo array con los valores mayores a 10.

In [ ]:
lista = [3, 8, 15, 20, 7, 12, 18, 1]
array = np.array(lista)

arraymayor_10 = array[array > 10]
print(arraymayor_10)

[15 20 12 18]


# 9. Crear una matriz 4x4 con números del 1 al 16. Extraer la segunda fila, la tercera columna y el elemento (2,2).

In [13]:
matriz = np.arange(1, 17).reshape(4, 4)
print("matriz", matriz)

segunda_fila = matriz[1, :]
print("segunda fila", segunda_fila)

tercera_columna = matriz[:, 2]
print("tercera fila", tercera_columna)

elemento_2_2 = matriz[2, 2]
print("elemento (2,2)", elemento_2_2)

matriz [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
segunda fila [5 6 7 8]
tercera fila [ 3  7 11 15]
elemento (2,2) 11


# 10. Crear una matriz 3x3 con números aleatorios entre 1 y 10. Calcular la suma de cada fila y de cada columna.

In [15]:
m = np.random.randint(1,11, size=(3,3))
print("matriz", m)
#axis = 1 fila
suma_filas = np.sum(m, axis=1)
print("suma de cada fila", suma_filas)

#axis = 0 columna
suma_columnas = np.sum(m, axis=0)
print("Suma de cada columna", suma_columnas)

matriz [[3 6 5]
 [4 5 9]
 [9 1 8]]
suma de cada fila [14 18 18]
Suma de cada columna [16 12 22]


# 11. Dado el array [2,5,8,11,14,17], reemplazar los valores mayores a 10 por -1.

In [ ]:
a = np.array([2,5,8,11,14,17])
a[a > 10]= -1
print(a)

[ 2  5  8 -1 -1 -1]


# 12. Crear un array con números del 1 al 30 y obtener un nuevo array que contenga solo los números pares.

In [5]:
array = np.arange(1,31)
print(array)
array_pares = array[array % 2 == 0]
print("array con pares",array_pares)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
array con pares [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


# 13. Crear dos matrices A (2x3) y B (3x2) y calcular su producto matricial.

In [3]:
A = np.random.randint(1,11, size=(2,3))
print(A)
B = np.random.randint(1,11, size=(3,2))
print(B)

Producto_matricial = np.dot(A,B)
print("Producto Matricial", Producto_matricial)

[[5 9 5]
 [5 3 9]]
[[ 4 10]
 [ 8  7]
 [10 10]]
Producto Matricial [[142 163]
 [134 161]]


# 14. Crear una matriz 4x4 con números aleatorios entre 0 y 1. Mostrar el valor máximo y el mínimo.

In [8]:
M = np.random.rand(4,4)
print("Matriz",M)
print("Min:", M.min())
print("Max:", M.max())

Matriz [[0.92873436 0.46662984 0.53972274 0.86498793]
 [0.33370231 0.04878367 0.45952805 0.55119696]
 [0.65968572 0.23809427 0.34638669 0.02049118]
 [0.35749813 0.05701703 0.28150204 0.63548825]]
Min: 0.020491176847678427
Max: 0.9287343641543094


# 15. Dado el array [10,20,30,40,50], normalizar los valores usando (valor - minimo) / (maximo - minimo).

In [9]:
array = np.array([10,20,30,40,50])
print(array)
array_normalizado = (array - array.min()) / (array.max() - array.min())
print("normalizado",array_normalizado)

[10 20 30 40 50]
normalizado [0.   0.25 0.5  0.75 1.  ]


# 16. Crear un array con 10 números aleatorios entre 1 y 100. Mostrar el array original y el array ordenado.

In [4]:
a = np.random.randint(1,101, size= 10)
print("array normal", a)

a_ordenado = np.sort(a)
print("array ordenado", a_ordenado)


array normal [16 79 29 42 16 85 69 92 72 71]
array ordenado [16 16 29 42 69 71 72 79 85 92]


# 17. Dado el array [1,2,2,3,3,3,4,4,4,4], calcular cuántas veces aparece cada número.

In [4]:
a = np.array([1,2,2,3,3,3,4,4,4,4])
valores, cantidades = np.unique(a, return_counts=True)
print("valores unicos",valores)
print("cantidades que salen",cantidades)

valores unicos [1 2 3 4]
cantidades que salen [1 2 3 4]


# 18. Crear la matriz [[1,2,3],[4,5,6]] y calcular su transpuesta.

In [3]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)

Transpuesta = matriz.T
print("transpuesta", Transpuesta )

[[1 2 3]
 [4 5 6]]
transpuesta [[1 4]
 [2 5]
 [3 6]]


# 19. Dados A=[5,10,15,20] y B=[3,10,18,20], crear un array booleano indicando en qué posiciones son iguales.

In [5]:
A = np.array([5,10,15,20])
B= np.array([3,10,18,20])

resultado = A == B

print("A:", A)
print("B:", B)
print("Iguales?", resultado)

A: [ 5 10 15 20]
B: [ 3 10 18 20]
Iguales? [False  True False  True]


# 20. Crear una matriz 5x3 con números aleatorios entre 1 y 50 y calcular el promedio de cada columna.

In [6]:
m = np.random.randint(1,51, size=(5,3))
print("matriz", m)
print("promedio de cada columna", m.mean(axis=0))

matriz [[33  7 22]
 [18 21 34]
 [26 34 41]
 [36 35 42]
 [38 16 37]]
promedio de cada columna [30.2 22.6 35.2]
